### ISSUE TITLE
starling 2.0.1   mobile 

### ISSUE THREAD

**Issue by leefj** [joshtynjala/monsterdebugger-client-starling#5]
HI josh, I use then  monster debugger in my App
it seems  not work on starling 2.0.1 mobile app,debug with AIR simulator

**Comment by joshtynjala** [comment]
I have successfully tested mobile apps on desktop in the AIR simulator. Be sure to update to the latest SWCs, though. The old ones are not compatible.

**Comment by leefj** [comment]
this morning i replace the MonsterDebuggerMobile.SWC with MonsterDebugger.SWC in my mobile project it works.

Is  MonsterDebuggerMobile.SWC only use  when i package app to a real physical device ?
if i debug my app on desktop i should use  MonsterDebugger.swc ?

**Comment by joshtynjala** [comment]
Yeah, I think MonsterDebuggerMobile.SWC is supposed to be used when running on a physical mobile evice.

**Comment by leefj** [comment]
HimJosh 
I put the MonsterDebuggerMobile.SWC in to my mobile project class path, it did not work.
then i put MonsterDebugger.SWC in to my mobile project class path,it works and i saw my trace message in Monster Debugger console ,BUT APP crashed. 
so sad !!!! 

iOS 9.3.4, iPhone6 , 

this is code:

MonsterDebugger.initialize(this,"192.168.2.8");
MonsterDebugger.trace(this, "Hello World!");

could give any suggestion?

**Comment by leefj** [comment]
I have do more test now: iPhone 6, AIR SDK 22, mobile project;

1) use starling 1.9  and  MonsterDebugger.swc      saw trace msg in Monster Debugger console in the new tab

2) use starling 1.9  and  MonsterDebuggerMobile.swc     nothing, no new tab in  Monster Debugger

3) use starling 2.x  and  MonsterDebuggerMobile.swc     nothing, no new tab in  Monster Debugger

4) use starling 2.x  and  MonsterDebuggerMobile.swc     nothing, no new tab in  Monster Debugger

these swf file is down load from your github page

**Comment by joshtynjala** [comment]
I did not write the original network code, and I did not modify it in any way. I only added support for the Starling display list. I do not know why it would not connect.

**Comment by leefj** [comment]
hi josh ,I solved the problem, run the initialize code  later ,it work ok now.

thanks
